#---------------------------------#
#      General Configuration      #
#---------------------------------#
version: 0.54.{build}

branches:
  only:
    - master

#---------------------------------#
#    Environment Configuration    #
#---------------------------------#
image: Visual Studio 2017

configuration: 
 - Release
 - Debug
platform: 
  - x64
  - x86

#---------------------------------#
#       Build Configuration       #
#---------------------------------#
build:
  parallel: true
  verbosity: normal
